/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import Sonidos.Sonido;
import TDA.Aire;
import TDA.Compresor;
import TDA.ControlRemoto;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Componentes extends javax.swing.JFrame {
    public static Aire aireAcondicionado =null;
    private Sonido sonidoFondo;
    private String[] args;

    /**
     * Creates new form Componentes
     */
    public Componentes() {
        args=null;
        sonidoFondo = new Sonido(this, 1);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        sonidoFondo.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jpFondo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCompresor = new javax.swing.JLabel();
        lblTipoCompresor = new javax.swing.JLabel();
        cboTipoCompresor = new javax.swing.JComboBox();
        btnEnsamblar = new javax.swing.JButton();
        lblMarcaCompresor = new javax.swing.JLabel();
        cboMarcaCompresor = new javax.swing.JComboBox();
        lblBTUCompresor = new javax.swing.JLabel();
        lblColorCompresor = new javax.swing.JLabel();
        lblVelocidadCompresor = new javax.swing.JLabel();
        cboBTUCompresor = new javax.swing.JComboBox();
        cboColorCompresor = new javax.swing.JComboBox();
        cboVelocidadCompresor = new javax.swing.JComboBox();
        lblCondensador = new javax.swing.JLabel();
        lblTipoCondensador = new javax.swing.JLabel();
        lblMarcaCondensador = new javax.swing.JLabel();
        lblVatiosCondensador = new javax.swing.JLabel();
        cboMarcaCondensador = new javax.swing.JComboBox();
        cboVatiosCondensador = new javax.swing.JComboBox();
        cboTipoCondesador = new javax.swing.JComboBox();
        lblBtuCondensador = new javax.swing.JLabel();
        cboBtuCondensador = new javax.swing.JComboBox();
        lblHertzCondensador = new javax.swing.JLabel();
        cboHertzCondensador = new javax.swing.JComboBox();
        lblValvula = new javax.swing.JLabel();
        lblTipoValvula = new javax.swing.JLabel();
        cboTipoValvula = new javax.swing.JComboBox();
        lblMarcaValvula = new javax.swing.JLabel();
        cboMarcaValvula = new javax.swing.JComboBox();
        lblModeloValvula = new javax.swing.JLabel();
        lblToneladaValvula = new javax.swing.JLabel();
        cboModeloValvula = new javax.swing.JComboBox();
        cboToneladaValvula = new javax.swing.JComboBox();
        lblEvaporador = new javax.swing.JLabel();
        lblTipoEvapordor = new javax.swing.JLabel();
        cboTipoEvapordor = new javax.swing.JComboBox();
        cboMarcaEvapordor = new javax.swing.JComboBox();
        lblMarcaEvapordor = new javax.swing.JLabel();
        lblModeloEvapordor = new javax.swing.JLabel();
        lblBtuEvapordor = new javax.swing.JLabel();
        cboBtuEvapordor = new javax.swing.JComboBox();
        cboModeloEvapordor = new javax.swing.JComboBox();
        lblRefrigerante = new javax.swing.JLabel();
        lblCodigoRefrigerante = new javax.swing.JLabel();
        lblKilogramosRefrigerante = new javax.swing.JLabel();
        cboKilogramosRefrigerante = new javax.swing.JComboBox();
        lblRecargabilidadRefrigerante = new javax.swing.JLabel();
        cboRecargabilidadRefrigerante = new javax.swing.JComboBox();
        cboCodigoRefrigerante = new javax.swing.JComboBox();
        btnCancelar = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpFondo.setBackground(new java.awt.Color(0, 102, 102));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo.setText("Componentes");

        lblCompresor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCompresor.setText("Compresor");

        lblTipoCompresor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTipoCompresor.setText("Tipo");

        cboTipoCompresor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Centrifugo", "Reciprocante" }));

        btnEnsamblar.setText("Ensamblar");
        btnEnsamblar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnsamblarMouseClicked(evt);
            }
        });

        lblMarcaCompresor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMarcaCompresor.setText("Marca");

        cboMarcaCompresor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SANYO", "GMCC(TOSHIBA)", "BRISTOL", "TECUMSEH", "CHEVROLET", "FORD", "FIAT", "TOYOTA" }));

        lblBTUCompresor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBTUCompresor.setText("BTU");

        lblColorCompresor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblColorCompresor.setText("Color");

        lblVelocidadCompresor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblVelocidadCompresor.setText("Velocidad");

        cboBTUCompresor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12000", "18000", "24000" }));

        cboColorCompresor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gris", "Negro" }));

        cboVelocidadCompresor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3500 rmp" }));

        lblCondensador.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCondensador.setText("Condensador");

        lblTipoCondensador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTipoCondensador.setText("Tipo");

        lblMarcaCondensador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMarcaCondensador.setText("Marca");

        lblVatiosCondensador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblVatiosCondensador.setText("Vatios");

        cboMarcaCondensador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "QUALITY", "LG", "CHEVROLET", "FORD", "FIAT", "TOYOTA" }));

        cboVatiosCondensador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "30W", "35W", "40W", "45W", "60W" }));

        cboTipoCondesador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ceramica", "Plastico", "Mica" }));

        lblBtuCondensador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBtuCondensador.setText("BTU");

        cboBtuCondensador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12000", "18000", "24000" }));

        lblHertzCondensador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblHertzCondensador.setText("Hertz");

        cboHertzCondensador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "60HZ" }));

        lblValvula.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblValvula.setText("Valvula de Expansión");

        lblTipoValvula.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTipoValvula.setText("Tipo");

        cboTipoValvula.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manual", "Termostatico", "Electromecanica" }));

        lblMarcaValvula.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMarcaValvula.setText("Marca");

        cboMarcaValvula.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EMERSON", "SPORLAND", "CHEVROLET", "FORD", "FIAT", "TOYOTA" }));

        lblModeloValvula.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblModeloValvula.setText("Modelo");

        lblToneladaValvula.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblToneladaValvula.setText("TRF");

        cboModeloValvula.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TCLE 5 HC", "OVE-40-N" }));

        cboToneladaValvula.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "10", "40" }));

        lblEvaporador.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEvaporador.setText("Evaporador");

        lblTipoEvapordor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTipoEvapordor.setText("Tipo");

        cboTipoEvapordor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aletados", "Expansion Seca" }));

        cboMarcaEvapordor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GENERAL PLUS", "WESTINGHOUSE", "CHEVROLET", "FORD", "FIAT", "TOYOTA" }));

        lblMarcaEvapordor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMarcaEvapordor.setText("Marca");

        lblModeloEvapordor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblModeloEvapordor.setText("Modelo");

        lblBtuEvapordor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBtuEvapordor.setText("BTU");

        cboBtuEvapordor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12000", "18000", "24000" }));

        cboModeloEvapordor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KF-43GW", "C-KF-32GW" }));

        lblRefrigerante.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblRefrigerante.setText("Refrigerante");

        lblCodigoRefrigerante.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCodigoRefrigerante.setText("Código");

        lblKilogramosRefrigerante.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKilogramosRefrigerante.setText("Kilogramos");

        cboKilogramosRefrigerante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.750 kg", "1 kg", "13 kg" }));

        lblRecargabilidadRefrigerante.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblRecargabilidadRefrigerante.setText("Recargabilidad");

        cboRecargabilidadRefrigerante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));

        cboCodigoRefrigerante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "R-12", "R-22", "R-500", "R-502" }));

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpFondoLayout = new javax.swing.GroupLayout(jpFondo);
        jpFondo.setLayout(jpFondoLayout);
        jpFondoLayout.setHorizontalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoCompresor)
                            .addComponent(lblMarcaCompresor))
                        .addGap(27, 27, 27)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboMarcaCompresor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboTipoCompresor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addComponent(lblMarcaEvapordor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboMarcaEvapordor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addComponent(lblTipoEvapordor)
                        .addGap(18, 18, 18)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEvaporador)
                            .addComponent(cboTipoEvapordor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVelocidadCompresor)
                            .addComponent(lblColorCompresor)
                            .addComponent(lblBTUCompresor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboBTUCompresor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboColorCompresor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboVelocidadCompresor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModeloEvapordor)
                            .addComponent(lblBtuEvapordor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboBtuEvapordor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboModeloEvapordor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addComponent(lblCodigoRefrigerante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMarcaValvula)
                                            .addComponent(lblModeloValvula)
                                            .addComponent(lblToneladaValvula))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboModeloValvula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboMarcaValvula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboToneladaValvula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblValvula))
                                .addGap(53, 53, 53))
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addComponent(btnEnsamblar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addComponent(lblTipoValvula)
                                        .addGap(22, 22, 22)
                                        .addComponent(cboTipoValvula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipoCondensador)
                                    .addComponent(lblMarcaCondensador))
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(lblTitulo))
                                    .addComponent(lblCondensador)
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboMarcaCondensador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboTipoCondesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblHertzCondensador)
                                .addGap(23, 23, 23)
                                .addComponent(cboHertzCondensador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblRefrigerante)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVatiosCondensador)
                                    .addComponent(lblBtuCondensador))
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cboVatiosCondensador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cboBtuCondensador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRecargabilidadRefrigerante)
                                    .addComponent(lblKilogramosRefrigerante))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboKilogramosRefrigerante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboRecargabilidadRefrigerante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboCodigoRefrigerante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblCompresor)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpFondoLayout.setVerticalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(43, 43, 43)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompresor)
                    .addComponent(lblCondensador)
                    .addComponent(lblValvula))
                .addGap(18, 18, 18)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoCompresor)
                            .addComponent(cboTipoCompresor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMarcaCompresor)
                            .addComponent(cboMarcaCompresor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBTUCompresor)
                            .addComponent(cboBTUCompresor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoCondensador)
                            .addComponent(cboTipoCondesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboTipoValvula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipoValvula))
                        .addGap(18, 18, 18)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMarcaCondensador)
                            .addComponent(cboMarcaCondensador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMarcaValvula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMarcaValvula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVatiosCondensador)
                            .addComponent(cboVatiosCondensador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModeloValvula)
                            .addComponent(cboModeloValvula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblColorCompresor)
                            .addComponent(cboColorCompresor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBtuCondensador)
                            .addComponent(cboBtuCondensador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblToneladaValvula)
                            .addComponent(cboToneladaValvula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVelocidadCompresor)
                    .addComponent(cboVelocidadCompresor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHertzCondensador)
                    .addComponent(cboHertzCondensador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEvaporador)
                    .addComponent(lblRefrigerante))
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoEvapordor)
                            .addComponent(cboTipoEvapordor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigoRefrigerante)
                            .addComponent(cboCodigoRefrigerante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboMarcaEvapordor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMarcaEvapordor))
                        .addGap(18, 18, 18)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModeloEvapordor)
                            .addComponent(cboModeloEvapordor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBtuEvapordor)
                            .addComponent(cboBtuEvapordor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboKilogramosRefrigerante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKilogramosRefrigerante))
                        .addGap(18, 18, 18)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRecargabilidadRefrigerante)
                            .addComponent(cboRecargabilidadRefrigerante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnEnsamblar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        sonidoFondo.Stop();
        this.dispose();
        MenuPrincipal.main(args);
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnEnsamblarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnsamblarMouseClicked
        sonidoFondo.Stop();
        cargarComponentes();
        Ensamblador.aireAcondicionado = aireAcondicionado;
        this.dispose();
        Ensamblador.main(args);
    }//GEN-LAST:event_btnEnsamblarMouseClicked
    
    public void cargarComponentes(){
        cargarCompresor();
        cargarCondensador();
        cargarEvaporador();
        cargarValvulaExpansion();
        cargarRefrigerante();
        
    }
   
    public void cargarRefrigerante(){
        
        aireAcondicionado.getRefrigerante().setCodigo(cboCodigoRefrigerante.getSelectedItem().toString());
        aireAcondicionado.getRefrigerante().setKilogramos(cboKilogramosRefrigerante.getSelectedItem().toString());
        aireAcondicionado.getRefrigerante().setRecargabilidad(cboRecargabilidadRefrigerante.getSelectedItem().toString());  
    }
    
    public void cargarCompresor(){
    
        aireAcondicionado.getCompresor().setTipo(cboTipoCompresor.getSelectedItem().toString());
        aireAcondicionado.getCompresor().setMarca(cboMarcaCompresor.getSelectedItem().toString());
        aireAcondicionado.getCompresor().setBTU(cboBTUCompresor.getSelectedItem().toString());
        aireAcondicionado.getCompresor().setColor(cboColorCompresor.getSelectedItem().toString());
        aireAcondicionado.getCompresor().setVelocidad(cboVelocidadCompresor.getSelectedItem().toString());
    
    }
    
    public void cargarCondensador(){
    
        aireAcondicionado.getCondensador().setTipo(cboTipoCondesador.getSelectedItem().toString());
        aireAcondicionado.getCondensador().setMarca(cboMarcaCondensador.getSelectedItem().toString());
        aireAcondicionado.getCondensador().setVatios(cboVatiosCondensador.getSelectedItem().toString());
        aireAcondicionado.getCondensador().setBTU(cboBtuCondensador.getSelectedItem().toString());
        aireAcondicionado.getCondensador().setHertz(cboHertzCondensador.getSelectedItem().toString());  
    
    }
    
    public void cargarValvulaExpansion(){
    
        aireAcondicionado.getValvulaDeExpansion().setTipo(cboTipoValvula.getSelectedItem().toString());
        aireAcondicionado.getValvulaDeExpansion().setMarca(cboMarcaValvula.getSelectedItem().toString());
        aireAcondicionado.getValvulaDeExpansion().setModelo(cboModeloValvula.getSelectedItem().toString());
        aireAcondicionado.getValvulaDeExpansion().setTRF(cboToneladaValvula.getSelectedItem().toString());
    }
    
    public void cargarEvaporador(){
    
        aireAcondicionado.getEvaporador().setTipo(cboTipoEvapordor.getSelectedItem().toString());
        aireAcondicionado.getEvaporador().setMarca(cboMarcaEvapordor.getSelectedItem().toString());
        aireAcondicionado.getEvaporador().setModelo(cboModeloEvapordor.getSelectedItem().toString());
        aireAcondicionado.getEvaporador().setBTU(cboBtuEvapordor.getSelectedItem().toString());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Componentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEnsamblar;
    private javax.swing.JComboBox cboBTUCompresor;
    private javax.swing.JComboBox cboBtuCondensador;
    private javax.swing.JComboBox cboBtuEvapordor;
    private javax.swing.JComboBox cboCodigoRefrigerante;
    private javax.swing.JComboBox cboColorCompresor;
    private javax.swing.JComboBox cboHertzCondensador;
    private javax.swing.JComboBox cboKilogramosRefrigerante;
    private javax.swing.JComboBox cboMarcaCompresor;
    private javax.swing.JComboBox cboMarcaCondensador;
    private javax.swing.JComboBox cboMarcaEvapordor;
    private javax.swing.JComboBox cboMarcaValvula;
    private javax.swing.JComboBox cboModeloEvapordor;
    private javax.swing.JComboBox cboModeloValvula;
    private javax.swing.JComboBox cboRecargabilidadRefrigerante;
    private javax.swing.JComboBox cboTipoCompresor;
    private javax.swing.JComboBox cboTipoCondesador;
    private javax.swing.JComboBox cboTipoEvapordor;
    private javax.swing.JComboBox cboTipoValvula;
    private javax.swing.JComboBox cboToneladaValvula;
    private javax.swing.JComboBox cboVatiosCondensador;
    private javax.swing.JComboBox cboVelocidadCompresor;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JLabel lblBTUCompresor;
    private javax.swing.JLabel lblBtuCondensador;
    private javax.swing.JLabel lblBtuEvapordor;
    private javax.swing.JLabel lblCodigoRefrigerante;
    private javax.swing.JLabel lblColorCompresor;
    private javax.swing.JLabel lblCompresor;
    private javax.swing.JLabel lblCondensador;
    private javax.swing.JLabel lblEvaporador;
    private javax.swing.JLabel lblHertzCondensador;
    private javax.swing.JLabel lblKilogramosRefrigerante;
    private javax.swing.JLabel lblMarcaCompresor;
    private javax.swing.JLabel lblMarcaCondensador;
    private javax.swing.JLabel lblMarcaEvapordor;
    private javax.swing.JLabel lblMarcaValvula;
    private javax.swing.JLabel lblModeloEvapordor;
    private javax.swing.JLabel lblModeloValvula;
    private javax.swing.JLabel lblRecargabilidadRefrigerante;
    private javax.swing.JLabel lblRefrigerante;
    private javax.swing.JLabel lblTipoCompresor;
    private javax.swing.JLabel lblTipoCondensador;
    private javax.swing.JLabel lblTipoEvapordor;
    private javax.swing.JLabel lblTipoValvula;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblToneladaValvula;
    private javax.swing.JLabel lblValvula;
    private javax.swing.JLabel lblVatiosCondensador;
    private javax.swing.JLabel lblVelocidadCompresor;
    // End of variables declaration//GEN-END:variables
}
