/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import Sonidos.Sonido;
import TDA.Aire;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Ensamblador extends javax.swing.JFrame {
    public static Aire aireAcondicionado = null;
    public static int numeroDeAiresAEnsamblar = 0;
    private Fondo imagenFondo;
    private int estacionActual;
    private int numeroDeAiresEnsamblados;
    Sonido sonidoFondo;
    private String[] args;
    

    /**
     * Creates new form Ensamblador
     */
    public Ensamblador() {
        args = null;
        imagenFondo = new Fondo("/imagenes/fondoEnsamblador.jpg");
        sonidoFondo = new Sonido(this, 1);
        
        initComponents();
        this.setSize(imagenFondo.getWidth(),imagenFondo.getHeight()+10);
        this.setResizable(false);
        jpFondo.add(imagenFondo);
        jpFondo.setOpaque(false);
        this.setLocationRelativeTo(null);
        prepararEstaciones();
        estacionActual = -1;
        numeroDeAiresEnsamblados =0;
        sonidoFondo.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFondo = new javax.swing.JPanel();
        jpPlacaEstacion0 = new javax.swing.JPanel();
        lblPlaca = new javax.swing.JLabel();
        lblTipoAire = new javax.swing.JLabel();
        jpPlacaEstacion1 = new javax.swing.JPanel();
        lblCompresor1 = new javax.swing.JLabel();
        jpPlacaEstacion2 = new javax.swing.JPanel();
        lblCompresor2 = new javax.swing.JLabel();
        lblEvaporador2 = new javax.swing.JLabel();
        jpPlacaEstacion3 = new javax.swing.JPanel();
        lblCompresor3 = new javax.swing.JLabel();
        lblEvaporador3 = new javax.swing.JLabel();
        lblCondensador3 = new javax.swing.JLabel();
        jpPlacaEstacion4 = new javax.swing.JPanel();
        lblCompresor4 = new javax.swing.JLabel();
        lblRefrigerante4 = new javax.swing.JLabel();
        lblEvaporador4 = new javax.swing.JLabel();
        lblCondensador4 = new javax.swing.JLabel();
        jpPlacaEstacion5 = new javax.swing.JPanel();
        lblCompresor5 = new javax.swing.JLabel();
        lblRefrigerante5 = new javax.swing.JLabel();
        lblEvaporador5 = new javax.swing.JLabel();
        lblCondensador5 = new javax.swing.JLabel();
        lblValvula5 = new javax.swing.JLabel();
        lblProductoFinal = new javax.swing.JLabel();
        lblNumeroDeAires = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        lblEstacion0 = new javax.swing.JLabel();
        lblEstacion1 = new javax.swing.JLabel();
        lblEstacion2 = new javax.swing.JLabel();
        lblEstacion3 = new javax.swing.JLabel();
        lblEstacion4 = new javax.swing.JLabel();
        lblEstacion5 = new javax.swing.JLabel();
        lblEstacion6 = new javax.swing.JLabel();
        lblEstacion7 = new javax.swing.JLabel();
        btnEmpezar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpFondo.setBackground(new java.awt.Color(0, 153, 51));

        jpPlacaEstacion0.setBackground(new java.awt.Color(255, 255, 255));

        lblPlaca.setText("Placa  De Aire ");

        lblTipoAire.setText("Tipo");

        javax.swing.GroupLayout jpPlacaEstacion0Layout = new javax.swing.GroupLayout(jpPlacaEstacion0);
        jpPlacaEstacion0.setLayout(jpPlacaEstacion0Layout);
        jpPlacaEstacion0Layout.setHorizontalGroup(
            jpPlacaEstacion0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlacaEstacion0Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpPlacaEstacion0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPlacaEstacion0Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTipoAire))
                    .addComponent(lblPlaca))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jpPlacaEstacion0Layout.setVerticalGroup(
            jpPlacaEstacion0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlacaEstacion0Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblPlaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTipoAire)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpPlacaEstacion1.setBackground(new java.awt.Color(255, 255, 255));

        lblCompresor1.setText("Compresor");

        javax.swing.GroupLayout jpPlacaEstacion1Layout = new javax.swing.GroupLayout(jpPlacaEstacion1);
        jpPlacaEstacion1.setLayout(jpPlacaEstacion1Layout);
        jpPlacaEstacion1Layout.setHorizontalGroup(
            jpPlacaEstacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPlacaEstacion1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(lblCompresor1)
                .addContainerGap())
        );
        jpPlacaEstacion1Layout.setVerticalGroup(
            jpPlacaEstacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPlacaEstacion1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(lblCompresor1)
                .addContainerGap())
        );

        jpPlacaEstacion2.setBackground(new java.awt.Color(255, 255, 255));

        lblCompresor2.setText("Compresor");

        lblEvaporador2.setText("Evaporador");

        javax.swing.GroupLayout jpPlacaEstacion2Layout = new javax.swing.GroupLayout(jpPlacaEstacion2);
        jpPlacaEstacion2.setLayout(jpPlacaEstacion2Layout);
        jpPlacaEstacion2Layout.setHorizontalGroup(
            jpPlacaEstacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlacaEstacion2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEvaporador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(lblCompresor2)
                .addContainerGap())
        );
        jpPlacaEstacion2Layout.setVerticalGroup(
            jpPlacaEstacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlacaEstacion2Layout.createSequentialGroup()
                .addComponent(lblEvaporador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCompresor2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPlacaEstacion3.setBackground(new java.awt.Color(255, 255, 255));

        lblCompresor3.setText("Compresor");

        lblEvaporador3.setText("Evaporador");

        lblCondensador3.setText("Condensador");

        javax.swing.GroupLayout jpPlacaEstacion3Layout = new javax.swing.GroupLayout(jpPlacaEstacion3);
        jpPlacaEstacion3.setLayout(jpPlacaEstacion3Layout);
        jpPlacaEstacion3Layout.setHorizontalGroup(
            jpPlacaEstacion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlacaEstacion3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEvaporador3)
                .addGap(11, 11, 11)
                .addGroup(jpPlacaEstacion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPlacaEstacion3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblCompresor3))
                    .addGroup(jpPlacaEstacion3Layout.createSequentialGroup()
                        .addComponent(lblCondensador3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpPlacaEstacion3Layout.setVerticalGroup(
            jpPlacaEstacion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlacaEstacion3Layout.createSequentialGroup()
                .addGroup(jpPlacaEstacion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEvaporador3)
                    .addComponent(lblCondensador3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCompresor3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPlacaEstacion4.setBackground(new java.awt.Color(255, 255, 255));

        lblCompresor4.setText("Compresor");

        lblRefrigerante4.setText("Refrigerante");

        lblEvaporador4.setText("Evaporador");

        lblCondensador4.setText("Condensador");

        javax.swing.GroupLayout jpPlacaEstacion4Layout = new javax.swing.GroupLayout(jpPlacaEstacion4);
        jpPlacaEstacion4.setLayout(jpPlacaEstacion4Layout);
        jpPlacaEstacion4Layout.setHorizontalGroup(
            jpPlacaEstacion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlacaEstacion4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPlacaEstacion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEvaporador4)
                    .addComponent(lblRefrigerante4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPlacaEstacion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCompresor4)
                    .addComponent(lblCondensador4)))
        );
        jpPlacaEstacion4Layout.setVerticalGroup(
            jpPlacaEstacion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlacaEstacion4Layout.createSequentialGroup()
                .addGroup(jpPlacaEstacion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEvaporador4)
                    .addComponent(lblCondensador4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPlacaEstacion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRefrigerante4)
                    .addComponent(lblCompresor4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPlacaEstacion5.setBackground(new java.awt.Color(255, 255, 255));

        lblCompresor5.setText("Compresor");

        lblRefrigerante5.setText("Refrigerante");

        lblEvaporador5.setText("Evaporador");

        lblCondensador5.setText("Condensador");

        lblValvula5.setText("Válvula");

        javax.swing.GroupLayout jpPlacaEstacion5Layout = new javax.swing.GroupLayout(jpPlacaEstacion5);
        jpPlacaEstacion5.setLayout(jpPlacaEstacion5Layout);
        jpPlacaEstacion5Layout.setHorizontalGroup(
            jpPlacaEstacion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlacaEstacion5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPlacaEstacion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEvaporador5)
                    .addComponent(lblRefrigerante5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPlacaEstacion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPlacaEstacion5Layout.createSequentialGroup()
                        .addComponent(lblValvula5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCompresor5))
                    .addGroup(jpPlacaEstacion5Layout.createSequentialGroup()
                        .addComponent(lblCondensador5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpPlacaEstacion5Layout.setVerticalGroup(
            jpPlacaEstacion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlacaEstacion5Layout.createSequentialGroup()
                .addGroup(jpPlacaEstacion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEvaporador5)
                    .addComponent(lblCondensador5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPlacaEstacion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRefrigerante5)
                    .addComponent(lblValvula5)
                    .addComponent(lblCompresor5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblProductoFinal.setText("Producto Final");

        lblNumeroDeAires.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblNumeroDeAires.setText("# 0");

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        lblEstacion0.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEstacion0.setText("Estacion 0(Tipo)");

        lblEstacion1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEstacion1.setText("Estación 1(Compresor)");

        lblEstacion2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEstacion2.setText("Estación 2(Evaporador)");

        lblEstacion3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEstacion3.setText("Estación 3(Condensador)");

        lblEstacion4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEstacion4.setText("Estación 4(Refrigerante)");

        lblEstacion5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEstacion5.setText("Estación 5(Válvula)");

        lblEstacion6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEstacion6.setText("  Estación 6(Control)");

        lblEstacion7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEstacion7.setText("Estación 7(Final)");

        btnEmpezar.setText("Empezar");
        btnEmpezar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmpezarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpFondoLayout = new javax.swing.GroupLayout(jpFondo);
        jpFondo.setLayout(jpFondoLayout);
        jpFondoLayout.setHorizontalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(lblEstacion5)
                        .addGap(40, 40, 40)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstacion6)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addComponent(jpPlacaEstacion5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblEstacion7)
                                .addGap(45, 45, 45)
                                .addComponent(lblProductoFinal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumeroDeAires)
                            .addComponent(btnCancelar)
                            .addComponent(btnEmpezar)))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jpPlacaEstacion0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jpPlacaEstacion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(lblEstacion1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jpPlacaEstacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(lblEstacion2))
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addGap(152, 152, 152)
                                        .addComponent(lblEstacion4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jpPlacaEstacion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEstacion3)
                                    .addComponent(jpPlacaEstacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(lblEstacion0)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpFondoLayout.setVerticalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpPlacaEstacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblEstacion2)))
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(lblEstacion3))
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jpPlacaEstacion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNumeroDeAires)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEmpezar)
                        .addGap(2, 2, 2)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(lblProductoFinal))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoLayout.createSequentialGroup()
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblEstacion7))
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpPlacaEstacion0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jpPlacaEstacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(lblEstacion1)))
                                .addGap(18, 18, 18)
                                .addComponent(lblEstacion0)
                                .addGap(63, 63, 63)
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpPlacaEstacion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpFondoLayout.createSequentialGroup()
                                        .addComponent(lblEstacion4)
                                        .addGap(120, 120, 120)
                                        .addComponent(lblEstacion6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpPlacaEstacion5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEstacion5))))
                        .addGap(30, 30, 30))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        sonidoFondo.Stop();
        this.dispose();
        MenuPrincipal.main(args);
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnEmpezarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpezarMouseClicked
        btnEmpezar.setText("Avanzar");
        Ensamblar();
    }//GEN-LAST:event_btnEmpezarMouseClicked

    public void Ensamblar(){
            estacionActual++;
            
            if(numeroDeAiresEnsamblados<numeroDeAiresAEnsamblar){
                
                switch(estacionActual){
                
                
                    case 0:{
                        apagarEstacion7();
                        encenderEstacion0();
                    }break;
                    
                    case 1:{
                        apagarEstacion0();
                        encenderEstacion1();
                    }break;
                    
                    case 2:{
                        apagarEstacion1();
                        encenderEstacion2();
                    }break;
                    
                    case 3:{
                        apagarEstacion2();
                        encenderEstacion3();
                    }break;
                    
                    case 4:{
                        apagarEstacion3();
                        encenderEstacion4();
                    }break;
                    
                    case 5:{
                        apagarEstacion4();
                        encenderEstacion5();
    
                    }break;
                    
                    case 6:{
                        
                        if(aireAcondicionado.getControlRemoto()!=null){
                            lblEstacion5.setForeground(Color.RED);
                            encenderEstacion6();
                            break;
                        }else{
                            apagarEstacion5();
                        }
                    }
                    
                    case 7:{
                        if(aireAcondicionado.getControlRemoto()!=null)
                            apagarEstacion5();
                        apagarEstacion6();
                        encenderEstacion7();
                        estacionActual=0;
                        numeroDeAiresEnsamblados++;
                        lblNumeroDeAires.setText("# "+numeroDeAiresEnsamblados);
                    }break;
                }
                
                
                
            }else{
                JOptionPane.showMessageDialog(this, "Ensamblaje finalizado con exito.");
                sonidoFondo.Stop();
                this.dispose();
                MenuPrincipal.main(args);
            }
    }
    
    public void encenderEstacion0(){
        lblEstacion0.setForeground(Color.GREEN);
        jpPlacaEstacion0.setVisible(true);
        lblTipoAire.setText(aireAcondicionado.getTipo());
        lblPlaca.setText("Placa  De Aire");
        jpPlacaEstacion0.setOpaque(true);
    }
    
    public void encenderEstacion1(){
    
        jpPlacaEstacion1.setOpaque(true);
        lblEstacion1.setForeground(Color.GREEN);
        lblCompresor1.setText("");
        lblCompresor1.setIcon(new ImageIcon(getClass().getResource("/imagenes/compresor"+aireAcondicionado.getCompresor().getColor()+".jpg")));
    }
    
    public void encenderEstacion2(){
        jpPlacaEstacion2.setOpaque(true);
        lblEstacion2.setForeground(Color.GREEN);
        lblEvaporador2.setText("");
        lblCompresor2.setText("");
        lblEvaporador2.setIcon(new ImageIcon(getClass().getResource("/imagenes/evaporador.jpg")));
        lblCompresor2.setIcon(new ImageIcon(getClass().getResource("/imagenes/compresor"+aireAcondicionado.getCompresor().getColor()+".jpg"))); 
    }
    
    public void encenderEstacion3(){
        jpPlacaEstacion3.setOpaque(true);
        lblEstacion3.setForeground(Color.GREEN);  
        lblEvaporador3.setText("");
        lblCondensador3.setText("");
        lblCompresor3.setText("");
        lblEvaporador3.setIcon(new ImageIcon(getClass().getResource("/imagenes/evaporador.jpg")));
        lblCondensador3.setIcon(new ImageIcon(getClass().getResource("/imagenes/condensador.jpg")));
        lblCompresor3.setIcon(new ImageIcon(getClass().getResource("/imagenes/compresor"+aireAcondicionado.getCompresor().getColor()+".jpg")));
    }
    
    public void encenderEstacion4(){
        jpPlacaEstacion4.setOpaque(true);
        lblEstacion4.setForeground(Color.GREEN);
        lblEvaporador4.setText("");
        lblCondensador4.setText("");
        lblRefrigerante4.setText("");
        lblCompresor4.setText("");
        lblEvaporador4.setIcon(new ImageIcon(getClass().getResource("/imagenes/evaporador.jpg")));
        lblCondensador4.setIcon(new ImageIcon(getClass().getResource("/imagenes/condensador.jpg")));
        lblRefrigerante4.setIcon(new ImageIcon(getClass().getResource("/imagenes/refrigerante.jpg")));
        lblCompresor4.setIcon(new ImageIcon(getClass().getResource("/imagenes/compresor"+aireAcondicionado.getCompresor().getColor()+".jpg")));
      
            
     
    }
    
    public void encenderEstacion5(){
        jpPlacaEstacion5.setOpaque(true);
        lblEstacion5.setForeground(Color.GREEN); 
        lblEvaporador5.setText("");
        lblCondensador5.setText("");
        lblRefrigerante5.setText("");
        lblValvula5.setText("");
        lblCompresor5.setText("");
        lblEvaporador5.setIcon(new ImageIcon(getClass().getResource("/imagenes/evaporador.jpg")));
        lblCondensador5.setIcon(new ImageIcon(getClass().getResource("/imagenes/condensador.jpg")));
        lblRefrigerante5.setIcon(new ImageIcon(getClass().getResource("/imagenes/refrigerante.jpg")));
        lblValvula5.setIcon(new ImageIcon(getClass().getResource("/imagenes/valvulaDeExpansion.jpg")));
        lblCompresor5.setIcon(new ImageIcon(getClass().getResource("/imagenes/compresor"+aireAcondicionado.getCompresor().getColor()+".jpg")));
         
    }
    
    public void encenderEstacion6(){
        
        lblEstacion6.setForeground(Color.GREEN);
        

    }
    
    public void encenderEstacion7(){
        lblProductoFinal.setText("");
        lblProductoFinal.setIcon(new ImageIcon(getClass().getResource("/imagenes/aire"+aireAcondicionado.getTipo()+".jpg")));
        lblEstacion7.setForeground(Color.GREEN);
        
    }
    
    public void prepararEstaciones(){
        apagarEstacion0();
        apagarEstacion1();
        apagarEstacion2();
        apagarEstacion3();
        apagarEstacion4();
        apagarEstacion5();
        apagarEstacion6();
        apagarEstacion7();
    }
    
    public void apagarEstacion0(){
        jpPlacaEstacion0.setOpaque(false);
        lblPlaca.setText("          \n           \n   \n  \n ");
        lblTipoAire.setText("       \n           \n   \n  \n ");
        lblEstacion0.setForeground(Color.RED); 
    }
    
    public void apagarEstacion1(){
        lblEstacion1.setForeground(Color.RED);
        jpPlacaEstacion1.setOpaque(false);
        lblCompresor1.setText("\n \n  \n \n \n  \n \n  ");
        lblCompresor1.setIcon(null);
    }

    public void apagarEstacion2(){
        lblEstacion2.setForeground(Color.RED); 
        jpPlacaEstacion2.setOpaque(false);
        lblCompresor2.setText("\n \n  \n \n \n  \n \n  ");
        lblEvaporador2.setText("\n \n  \n \n \n  \n \n  ");
        lblCompresor2.setIcon(null);
        lblEvaporador2.setIcon(null);
    }
    
    public void apagarEstacion3(){
        lblEstacion3.setForeground(Color.RED);
        jpPlacaEstacion3.setOpaque(false);
        lblCompresor3.setText("  \n   \n    \n   \n \n    \n \n  ");
        lblCondensador3.setText("   \n   \n  \n   \n \n    \n \n  ");
        lblEvaporador3.setText("  \n   \n  \n   \n \n    \n \n  ");
        lblCompresor3.setIcon(null);
        lblEvaporador3.setIcon(null);
        lblCondensador3.setIcon(null);
        
    }
    
    public void apagarEstacion4(){
        lblEstacion4.setForeground(Color.RED);
        jpPlacaEstacion4.setOpaque(false);
        lblCompresor4.setText("\n \n  \n \n \n  \n \n  ");
        lblCondensador4.setText("\n \n  \n \n \n  \n \n  ");
        lblEvaporador4.setText("\n \n  \n \n \n  \n \n  ");
        lblRefrigerante4.setText("\n \n  \n \n \n  \n \n  ");
        lblCondensador4.setIcon(null);
        lblEvaporador4.setIcon(null);
        lblCompresor4.setIcon(null);
        lblRefrigerante4.setIcon(null);
    }
    
    public void apagarEstacion5(){
        lblEstacion5.setForeground(Color.RED);
        jpPlacaEstacion5.setOpaque(false);
        lblCompresor5.setText("\n \n    \n \n \n    \n \n  ");
        lblCondensador5.setText("\n    \n  \n \n   \n  \n \n  ");
        lblEvaporador5.setText("\n \n    \n   \n   \n  \n \n  ");
        lblValvula5.setText("\n \n  \n \n \n    \n \n  ");
        lblRefrigerante5.setText("\n \n  \n  \n  \n  \n   \n    ");
        lblCondensador5.setIcon(null);
        lblEvaporador5.setIcon(null);
        lblCompresor5.setIcon(null);
        lblRefrigerante5.setIcon(null);
        lblValvula5.setIcon(null);
    }
    
    public void apagarEstacion6(){
        lblEstacion6.setForeground(Color.RED); 
        
        
    }
    
    public void apagarEstacion7(){
        lblEstacion7.setForeground(Color.RED);
        lblProductoFinal.setText("\n \n  \n \n \n  \n \n  ");
        lblProductoFinal.setIcon(null);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ensamblador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ensamblador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ensamblador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ensamblador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ensamblador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JPanel jpPlacaEstacion0;
    private javax.swing.JPanel jpPlacaEstacion1;
    private javax.swing.JPanel jpPlacaEstacion2;
    private javax.swing.JPanel jpPlacaEstacion3;
    private javax.swing.JPanel jpPlacaEstacion4;
    private javax.swing.JPanel jpPlacaEstacion5;
    private javax.swing.JLabel lblCompresor1;
    private javax.swing.JLabel lblCompresor2;
    private javax.swing.JLabel lblCompresor3;
    private javax.swing.JLabel lblCompresor4;
    private javax.swing.JLabel lblCompresor5;
    private javax.swing.JLabel lblCondensador3;
    private javax.swing.JLabel lblCondensador4;
    private javax.swing.JLabel lblCondensador5;
    private javax.swing.JLabel lblEstacion0;
    private javax.swing.JLabel lblEstacion1;
    private javax.swing.JLabel lblEstacion2;
    private javax.swing.JLabel lblEstacion3;
    private javax.swing.JLabel lblEstacion4;
    private javax.swing.JLabel lblEstacion5;
    private javax.swing.JLabel lblEstacion6;
    private javax.swing.JLabel lblEstacion7;
    private javax.swing.JLabel lblEvaporador2;
    private javax.swing.JLabel lblEvaporador3;
    private javax.swing.JLabel lblEvaporador4;
    private javax.swing.JLabel lblEvaporador5;
    private javax.swing.JLabel lblNumeroDeAires;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblProductoFinal;
    private javax.swing.JLabel lblRefrigerante4;
    private javax.swing.JLabel lblRefrigerante5;
    private javax.swing.JLabel lblTipoAire;
    private javax.swing.JLabel lblValvula5;
    // End of variables declaration//GEN-END:variables
}
