/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import Sonidos.Sonido;
import TDA.Aire;
import TDA.ControlRemoto;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private Sonido sonidoFondo;
    private String[] args;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        args=null;
        sonidoFondo = new Sonido(this, 1);
        initComponents();
        lblImagenTipoAire.setIcon(new ImageIcon(getClass().getResource("/imagenes/aireSplit.jpg")));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        sonidoFondo.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpFondo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        cboControlRemoto = new javax.swing.JComboBox();
        lblAireAcondicionado = new javax.swing.JLabel();
        cboTipoAireAcondicionado = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        lblTipoAire = new javax.swing.JLabel();
        lblMarcaControl = new javax.swing.JLabel();
        lblColorControl = new javax.swing.JLabel();
        btnSeleccionarComponentes = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        cboMarcaControl = new javax.swing.JComboBox();
        cboColorControl = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cboCodigosControl = new javax.swing.JComboBox();
        lblImagenTipoAire = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpFondo.setBackground(new java.awt.Color(0, 102, 102));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo.setText("Menu Principal");

        cboControlRemoto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));
        cboControlRemoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboControlRemotoActionPerformed(evt);
            }
        });

        lblAireAcondicionado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAireAcondicionado.setText("Aire Acondicionado");

        cboTipoAireAcondicionado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Split", "Ventana", "Automotriz" }));
        cboTipoAireAcondicionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoAireAcondicionadoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Control Remoto");

        lblTipoAire.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTipoAire.setText("Tipo");

        lblMarcaControl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMarcaControl.setText("Marca");

        lblColorControl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblColorControl.setText("Color");

        btnSeleccionarComponentes.setText("Seleccionar Componentes");
        btnSeleccionarComponentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeleccionarComponentesMouseClicked(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        cboMarcaControl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LG", "SAMSUNG", "HAIER", "CHEVROLET", "FORD", "FIAT", "TOYOTA" }));

        cboColorControl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blanco", "Negro", "Azul" }));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Códigos");

        cboCodigosControl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "20", "30", "40", "50" }));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Cantidad");

        txtCantidad.setText("1");

        javax.swing.GroupLayout jpFondoLayout = new javax.swing.GroupLayout(jpFondo);
        jpFondo.setLayout(jpFondoLayout);
        jpFondoLayout.setHorizontalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAireAcondicionado)
                            .addComponent(lblImagenTipoAire)
                            .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jpFondoLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCantidad))
                                .addGroup(jpFondoLayout.createSequentialGroup()
                                    .addComponent(lblTipoAire)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cboTipoAireAcondicionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnSeleccionarComponentes))
                        .addGap(39, 39, 39)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addComponent(lblMarcaControl)
                                .addGap(18, 18, 18)
                                .addComponent(cboMarcaControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpFondoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboControlRemoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpFondoLayout.createSequentialGroup()
                                    .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(lblColorControl))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cboCodigosControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cboColorControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lblTitulo)))
                .addGap(0, 45, Short.MAX_VALUE))
        );
        jpFondoLayout.setVerticalGroup(
            jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(20, 20, 20)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAireAcondicionado)
                    .addComponent(jLabel4)
                    .addComponent(cboControlRemoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboTipoAireAcondicionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMarcaControl)
                        .addComponent(cboMarcaControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTipoAire))
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cboCodigosControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblColorControl)
                            .addComponent(cboColorControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpFondoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblImagenTipoAire)
                        .addGap(14, 14, 14)
                        .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jpFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnSeleccionarComponentes))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        sonidoFondo.Stop();
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSeleccionarComponentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarComponentesMouseClicked
        
        Componentes.aireAcondicionado = new Aire(cboTipoAireAcondicionado.getSelectedItem().toString());
        if(cboControlRemoto.getSelectedItem().toString().equalsIgnoreCase("Si")){
            Componentes.aireAcondicionado.getControlRemoto().setColor(cboColorControl.getSelectedItem().toString());
            Componentes.aireAcondicionado.getControlRemoto().setMarca(cboMarcaControl.getSelectedItem().toString());
            Componentes.aireAcondicionado.getControlRemoto().setCantidadDeCodigos(cboCodigosControl.getSelectedItem().toString());
        }else{
            Componentes.aireAcondicionado.setControlRemoto(null);
        }
        
        if(cantidadValida()){
            sonidoFondo.Stop();
            this.dispose();
            Componentes.main(args);
        }else
            JOptionPane.showMessageDialog(this, "La cantidad debe ser\nun número natural\ndistinto de 0."
                                              ,"Cantidad inválida",1,new ImageIcon(getClass().getResource("/Imagenes/cantidadInvalida.gif")));
        
        
    }//GEN-LAST:event_btnSeleccionarComponentesMouseClicked

    private void cboControlRemotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboControlRemotoActionPerformed
        if(cboControlRemoto.getSelectedItem().toString().equalsIgnoreCase("No")){
            cboMarcaControl.setEnabled(false);
            cboCodigosControl.setEnabled(false);
            cboColorControl.setEnabled(false);
        }else{
            cboMarcaControl.setEnabled(true);
            cboCodigosControl.setEnabled(true);
            cboColorControl.setEnabled(true);
        }
    }//GEN-LAST:event_cboControlRemotoActionPerformed

    private void cboTipoAireAcondicionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoAireAcondicionadoActionPerformed
        lblImagenTipoAire.setIcon(new ImageIcon(getClass().getResource("/imagenes/aire"+cboTipoAireAcondicionado.getSelectedItem().toString()+".jpg")));
    }//GEN-LAST:event_cboTipoAireAcondicionadoActionPerformed

    public boolean cantidadValida(){
        try {
            Ensamblador.numeroDeAiresAEnsamblar = Integer.parseInt(txtCantidad.getText());
            if(Ensamblador.numeroDeAiresAEnsamblar>0)
                return true;
            else
                return false;
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccionarComponentes;
    private javax.swing.JComboBox cboCodigosControl;
    private javax.swing.JComboBox cboColorControl;
    private javax.swing.JComboBox cboControlRemoto;
    private javax.swing.JComboBox cboMarcaControl;
    private javax.swing.JComboBox cboTipoAireAcondicionado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JLabel lblAireAcondicionado;
    private javax.swing.JLabel lblColorControl;
    private javax.swing.JLabel lblImagenTipoAire;
    private javax.swing.JLabel lblMarcaControl;
    private javax.swing.JLabel lblTipoAire;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
